[theme]

# Primary accent for interactive elements
primaryColor = '#0073C2'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ededed'

# Color used for almost all text
textColor = '#000000'